version: "3"

services:
  swapi_be:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/csv_files:/app/csv_files

  swapi_fe:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
